name: '[PRT] Quality Engineering'

on:
  pull_request_target:
    branches:
      - main
      - master
    types:
      - labeled

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v3.1.0
    with:
      danger: true
      dangerRequireChangelog: false
      nodeLint: true
      nodeTest: false
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_storefront-permissions
      nodeSonarOrganization: vtex-apps
      cypress: false
      cyRunnerTimeOut: 45
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
