name: '[PSH] Quality Engineering'

on:
  push:
    branches:
      - master
      - main

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v3.1.0
    with:
      nodeLint: true
      nodeTest: false
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_storefront-permissions
      nodeSonarOrganization: vtex-apps
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
