name: '[SCH] Quality Engineering'

on:
  schedule:
    - cron: '30 3 * * SAT'
jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v2
    with:
      cypress: true
      cyRunnerTimeOut: 45
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
